/**
* Proyecto Software 2020-2021
* 
* Proyecto: Tres en raya 
* 
* Autor: Alberto Tena Litauszky (770079)
*/
package Vista.VistaMenu;

import java.beans.PropertyChangeListener;
import Controlador.OyenteVista;
import Modelo.*;
import Vista.JuegoVista;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class InicioVista extends JFrame implements PropertyChangeListener{
    
    private String usuario;
    private List<String> historial;
    private Juego juego;
    private OyenteVista oyenteVista;
    private static InicioVista instancia;
    
    private static final String NUEVA_PARTIDA = "Nueva partida";
    private static final String ESPERANDO_ADVERSARIO = 
            "Esperando adversario...";
    private static final String SALTO = "\n---------------------------"
            + "----------------------------------------------------\n";
    private static final String VACIO = "";
    /**
     * Creates new form InicioVista
     */
    private InicioVista(OyenteVista oyenteVista, Juego juego) {
        this.oyenteVista = oyenteVista;
        this.juego = juego;
        historial = new ArrayList<>();
        this.setTitle(Juego.VERSION);
        initComponents();
        ponerDatos();
        ponerIcono();
        juego.nuevoObservador(this);
        jLabel3.setEnabled(false);
        this.setLocationRelativeTo(null);
    }
    
    /*
    * Patron singleton
    */
    public static synchronized InicioVista
            instancia(OyenteVista oyenteIU, Juego juego) {
        if (instancia == null) {
            instancia = new InicioVista(oyenteIU, juego);
        }
        return instancia;
    }
    
    /*
    * Pone la ventana en la ultima ubicacion de la anterior       
    */
    public void ubicarVentana(Point p){
        this.setLocation(p);
    }        
            
    /*
    * Devuelve la ubicacion de la ventana      
    */
    public Point posicion(){
        return this.getLocation();
    }
    
    /*
    * Actualiza los contenedores de datos  
    */        
    private void ponerDatos(){
        String usuario = juego.devuelveUsuario();
        historial = juego.devuelveHistorial();
        if(usuario != null){
            this.usuario = usuario;
        }
        String informacion = "";
        for(String linea: historial){
            informacion = linea + SALTO + informacion;
     
        }
        jTextArea1.setText(informacion);
    }
    /*
    * Muestra el parametro 'mensaje' en una nueva ventana
    */
    private void mostrarMensaje(String mensaje){
     JOptionPane.showMessageDialog(this, mensaje, 
        Juego.VERSION, 
        JOptionPane.INFORMATION_MESSAGE);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(usuario);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        String informacion = "";
        for(String linea: historial){
            informacion = linea + SALTO + informacion;

        }
        jTextArea1.setText(informacion);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Historial de partidas");

        jButton1.setText("Buscar partida");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Desconectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Buscando partida..");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * Accion del boton para buscar partida
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        oyenteVista.eventoProducido(OyenteVista.Evento.BUSCAR_PARTIDA, VACIO);
    }//GEN-LAST:event_jButton1ActionPerformed
    /*
    * Accion del boton para cerrar sesion
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        oyenteVista.eventoProducido(OyenteVista.Evento.CERRAR_SESION, evt);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /*
    * Pone el icono de la aplicacion
    */
    public void ponerIcono(){
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage("img/icono.png");
        this.setIconImage(img);
        this.setTitle(Juego.VERSION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    /*
    * Recibe los cambios en el modelo
    */
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(Juego.ENCUENTRA_PARTIDA)) {
            boolean exito = (boolean)evt.getNewValue();
            if(exito){
                mostrarMensaje(NUEVA_PARTIDA);
                JuegoVista juegoVista =  
                        JuegoVista.instancia(oyenteVista, juego);
                juegoVista.ubicarVentana(posicion());
                juegoVista.visualizarVentana();
                jLabel3.setEnabled(false);
                this.setVisible(false);
            }else{
                mostrarMensaje(ESPERANDO_ADVERSARIO);
                jButton1.setEnabled(false);
                jLabel3.setEnabled(true);
            }
        }else if (evt.getPropertyName().equals(Juego.ACABAR_PARTIDA)){
            jButton1.setEnabled(true);
            jLabel3.setEnabled(false);
        }else if (evt.getPropertyName().equals(Juego.PEDIR_HISTORIAL)){
            ponerDatos();
        }else if(evt.getPropertyName().equals(Juego.CERRAR_SESION)){
            oyenteVista.eventoProducido(OyenteVista.Evento.SALIR, evt);
        }
    }    
}
